image: docker:git
services:
  - docker:dind

stages:
  - build

build:
  stage: build
  image: docker:git
  services:
    - docker:dind
  script:
    - docker login -u $CI_USERNAME -p $CI_PASSWORD
    - docker build -t $CI_REGISTRY_IMAGE:$CI_BUILD_REF .
    - docker push $CI_REGISTRY_IMAGE:$CI_BUILD_REF