variables:
  STAGING_NS: gl-staging
  PROD_NS: gl-prod

stages:
  - build
  - staging

build:
  stage: build
  image: docker:git
  services:
    - docker:dind
  script:
    - docker login -u $CI_USERNAME -p $CI_PASSWORD
    - docker build -t $CI_REGISTRY_IMAGE:$CI_BUILD_REF .
    - docker push $CI_REGISTRY_IMAGE:$CI_BUILD_REF

staging:
  image: lehtux/cloud-sdk
  stage: staging
  environment: staging
  script:
    - kubectl get pods
    - envsubst < kubernetes/deployment.yml | kubectl apply -f -