stages:
  - build

build:
  stage: test
  image: docker:dind
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay
    DOCKER_HOST: tcp://localhost:2375
  script:
    - docker build -t foobar .