image: golang:latest

variables:
  PROD_PROJECT_URL: glawesome

before_script:
  - export STAGING_PROJECT_URL="${CI_BUILD_ID}.staging"

stages:
  - test
  - build
  - release
  - staging

test:
  stage: test
  script:
    - go test

build:
  stage: build
  script:
    - go build -o main
  artifacts:
    paths:
      - main

release:
  stage: release
  image: docker:git
  services:
    - docker:dind
  script:
    - docker login -u $CI_USERNAME -p $CI_PASSWORD
    - docker build -t $CI_REGISTRY_IMAGE:$CI_BUILD_REF .
    - docker push $CI_REGISTRY_IMAGE:$CI_BUILD_REF

staging:
  variables:
    PROJECT_URL: "{$STAGING_PROJECT_URL}"
  image: lehtux/cloud-sdk
  stage: staging
  environment: staging
  dependencies: []
  script:
    - kubectl config set-cluster k8s --server="${SERVER}"
    - kubectl config set-cluster k8s --certificate-authority=${CERTIFICATE_AUTHORITY_DATA}
    - kubectl config set-credentials gitlab --token="${USER_TOKEN}"
    - kubectl config set-context default --cluster=k8s --user gitlab
    - kubectl config use-context default
    - envsubst < kubernetes/deployment.yml | kubectl apply -f -