image: docker:git

services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://localhost:2376
  DOCKER_DRIVER: overlay2

before_script:
  - printenv
  - docker info
  - docker version

build:
  stage: build
  script:
    - docker build -t my-docker-image .
